name: Build Stock APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Stock Debug APK
        working-directory: android
        run: ./gradlew assembleStockDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tustock-stock-debug
          path: android/app/build/outputs/apk/stock/debug/*.apk
